sources:
  - type: gitlab
    url: ""
    config:
      token: ""
  - type: github
    config:
      token: ""
      exclude:
        - exluded_repo
      exclude_orgs:
        - excluded_org
elastic:
  url: https://localhost:9200
  username: user
  password: pass
  cert_location: cert/http_ca.crt
  index: gitsync
loglevel: INFO
