sources:
  - type: gitlab
    url: ""
    config:
      token: ""
elastic:
  url: https://localhost:9200
  username: user
  password: pass
  cert_location: cert/http_ca.crt
  index: gitsync
loglevel: INFO
